name: Upload data to Algolia index

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Build site
        run: hugo
      - name: Upload data
        working-directory: ./algolia
        run: |
          npm install
          npm run data-upload -- -c \
            -f ../public/index.json \
            -a 72C1FEBFMX \
            -k ${{ secrets.ALGOLIA_ADMIN_API_KEY }} \
            -n budimanjojo_com
